// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: protos_enum/enums.proto

package protos_enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CivilLevel int32

const (
	CivilLevel_CL_Bronze CivilLevel = 0
	CivilLevel_CL_Iron   CivilLevel = 1
	CivilLevel_CL_Sliver CivilLevel = 2
	CivilLevel_CL_Gold   CivilLevel = 3
)

// Enum value maps for CivilLevel.
var (
	CivilLevel_name = map[int32]string{
		0: "CL_Bronze",
		1: "CL_Iron",
		2: "CL_Sliver",
		3: "CL_Gold",
	}
	CivilLevel_value = map[string]int32{
		"CL_Bronze": 0,
		"CL_Iron":   1,
		"CL_Sliver": 2,
		"CL_Gold":   3,
	}
)

func (x CivilLevel) Enum() *CivilLevel {
	p := new(CivilLevel)
	*p = x
	return p
}

func (x CivilLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CivilLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_enum_enums_proto_enumTypes[0].Descriptor()
}

func (CivilLevel) Type() protoreflect.EnumType {
	return &file_protos_enum_enums_proto_enumTypes[0]
}

func (x CivilLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CivilLevel.Descriptor instead.
func (CivilLevel) EnumDescriptor() ([]byte, []int) {
	return file_protos_enum_enums_proto_rawDescGZIP(), []int{0}
}

type State int32

const (
	State_Broken   State = 0
	State_Progress State = 1
	State_Stop     State = 2
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "Broken",
		1: "Progress",
		2: "Stop",
	}
	State_value = map[string]int32{
		"Broken":   0,
		"Progress": 1,
		"Stop":     2,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_enum_enums_proto_enumTypes[1].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_protos_enum_enums_proto_enumTypes[1]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_protos_enum_enums_proto_rawDescGZIP(), []int{1}
}

type WorldType int32

const (
	WorldType_Planet WorldType = 0
	WorldType_Comet  WorldType = 1
	WorldType_Star   WorldType = 2
)

// Enum value maps for WorldType.
var (
	WorldType_name = map[int32]string{
		0: "Planet",
		1: "Comet",
		2: "Star",
	}
	WorldType_value = map[string]int32{
		"Planet": 0,
		"Comet":  1,
		"Star":   2,
	}
)

func (x WorldType) Enum() *WorldType {
	p := new(WorldType)
	*p = x
	return p
}

func (x WorldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorldType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_enum_enums_proto_enumTypes[2].Descriptor()
}

func (WorldType) Type() protoreflect.EnumType {
	return &file_protos_enum_enums_proto_enumTypes[2]
}

func (x WorldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorldType.Descriptor instead.
func (WorldType) EnumDescriptor() ([]byte, []int) {
	return file_protos_enum_enums_proto_rawDescGZIP(), []int{2}
}

var File_protos_enum_enums_proto protoreflect.FileDescriptor

var file_protos_enum_enums_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e,
	0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x44, 0x0a, 0x0a, 0x43, 0x69, 0x76,
	0x69, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4c, 0x5f, 0x42, 0x72,
	0x6f, 0x6e, 0x7a, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4c, 0x5f, 0x49, 0x72, 0x6f,
	0x6e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4c, 0x5f, 0x53, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4c, 0x5f, 0x47, 0x6f, 0x6c, 0x64, 0x10, 0x03, 0x2a,
	0x2b, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x72, 0x6f, 0x6b,
	0x65, 0x6e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x10, 0x02, 0x2a, 0x2c, 0x0a, 0x09,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x6c, 0x61,
	0x6e, 0x65, 0x74, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x10, 0x01,
	0x12, 0x08, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x72, 0x10, 0x02, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x61, 0x6f, 0x67, 0x75, 0x61, 0x6e,
	0x67, 0x64, 0x75, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x65, 0x64, 0x69, 0x74,
	0x6f, 0x72, 0x2f, 0x70, 0x62, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5f,
	0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_enum_enums_proto_rawDescOnce sync.Once
	file_protos_enum_enums_proto_rawDescData = file_protos_enum_enums_proto_rawDesc
)

func file_protos_enum_enums_proto_rawDescGZIP() []byte {
	file_protos_enum_enums_proto_rawDescOnce.Do(func() {
		file_protos_enum_enums_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_enum_enums_proto_rawDescData)
	})
	return file_protos_enum_enums_proto_rawDescData
}

var file_protos_enum_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protos_enum_enums_proto_goTypes = []any{
	(CivilLevel)(0), // 0: CivilLevel
	(State)(0),      // 1: State
	(WorldType)(0),  // 2: WorldType
}
var file_protos_enum_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_enum_enums_proto_init() }
func file_protos_enum_enums_proto_init() {
	if File_protos_enum_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_enum_enums_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_enum_enums_proto_goTypes,
		DependencyIndexes: file_protos_enum_enums_proto_depIdxs,
		EnumInfos:         file_protos_enum_enums_proto_enumTypes,
	}.Build()
	File_protos_enum_enums_proto = out.File
	file_protos_enum_enums_proto_rawDesc = nil
	file_protos_enum_enums_proto_goTypes = nil
	file_protos_enum_enums_proto_depIdxs = nil
}
