// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: protos_animal/animal.proto

package protos_animal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnimalType int32

const (
	AnimalType_AT_Dog      AnimalType = 0
	AnimalType_AT_Cat      AnimalType = 1
	AnimalType_AT_Elephant AnimalType = 2
)

// Enum value maps for AnimalType.
var (
	AnimalType_name = map[int32]string{
		0: "AT_Dog",
		1: "AT_Cat",
		2: "AT_Elephant",
	}
	AnimalType_value = map[string]int32{
		"AT_Dog":      0,
		"AT_Cat":      1,
		"AT_Elephant": 2,
	}
)

func (x AnimalType) Enum() *AnimalType {
	p := new(AnimalType)
	*p = x
	return p
}

func (x AnimalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnimalType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_animal_animal_proto_enumTypes[0].Descriptor()
}

func (AnimalType) Type() protoreflect.EnumType {
	return &file_protos_animal_animal_proto_enumTypes[0]
}

func (x AnimalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnimalType.Descriptor instead.
func (AnimalType) EnumDescriptor() ([]byte, []int) {
	return file_protos_animal_animal_proto_rawDescGZIP(), []int{0}
}

type Animal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  *AnimalType `protobuf:"varint,2,opt,name=type,proto3,enum=AnimalType,oneof" json:"type,omitempty"`
	Count *uint32     `protobuf:"varint,3,opt,name=count,proto3,oneof" json:"count,omitempty"`
	Foods []string    `protobuf:"bytes,4,rep,name=foods,proto3" json:"foods,omitempty"`
}

func (x *Animal) Reset() {
	*x = Animal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_animal_animal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Animal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Animal) ProtoMessage() {}

func (x *Animal) ProtoReflect() protoreflect.Message {
	mi := &file_protos_animal_animal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Animal.ProtoReflect.Descriptor instead.
func (*Animal) Descriptor() ([]byte, []int) {
	return file_protos_animal_animal_proto_rawDescGZIP(), []int{0}
}

func (x *Animal) GetType() AnimalType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return AnimalType_AT_Dog
}

func (x *Animal) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *Animal) GetFoods() []string {
	if x != nil {
		return x.Foods
	}
	return nil
}

var File_protos_animal_animal_proto protoreflect.FileDescriptor

var file_protos_animal_animal_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5f, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2f,
	0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x06,
	0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x48, 0x00, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x6f, 0x64, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6f, 0x6f, 0x64, 0x73, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2a, 0x35, 0x0a, 0x0a, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a,
	0x0a, 0x06, 0x41, 0x54, 0x5f, 0x44, 0x6f, 0x67, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x54,
	0x5f, 0x43, 0x61, 0x74, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x54, 0x5f, 0x45, 0x6c, 0x65,
	0x70, 0x68, 0x61, 0x6e, 0x74, 0x10, 0x02, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x61, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x67, 0x64, 0x75,
	0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2f,
	0x70, 0x62, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5f, 0x61, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_animal_animal_proto_rawDescOnce sync.Once
	file_protos_animal_animal_proto_rawDescData = file_protos_animal_animal_proto_rawDesc
)

func file_protos_animal_animal_proto_rawDescGZIP() []byte {
	file_protos_animal_animal_proto_rawDescOnce.Do(func() {
		file_protos_animal_animal_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_animal_animal_proto_rawDescData)
	})
	return file_protos_animal_animal_proto_rawDescData
}

var file_protos_animal_animal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_animal_animal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_animal_animal_proto_goTypes = []any{
	(AnimalType)(0), // 0: AnimalType
	(*Animal)(nil),  // 1: Animal
}
var file_protos_animal_animal_proto_depIdxs = []int32{
	0, // 0: Animal.type:type_name -> AnimalType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_animal_animal_proto_init() }
func file_protos_animal_animal_proto_init() {
	if File_protos_animal_animal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_animal_animal_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Animal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_animal_animal_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_animal_animal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_animal_animal_proto_goTypes,
		DependencyIndexes: file_protos_animal_animal_proto_depIdxs,
		EnumInfos:         file_protos_animal_animal_proto_enumTypes,
		MessageInfos:      file_protos_animal_animal_proto_msgTypes,
	}.Build()
	File_protos_animal_animal_proto = out.File
	file_protos_animal_animal_proto_rawDesc = nil
	file_protos_animal_animal_proto_goTypes = nil
	file_protos_animal_animal_proto_depIdxs = nil
}
