// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: proto_editor_option.proto

package protodef

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListOpType int32

const (
	ListOpType_None   ListOpType = 0
	ListOpType_Insert ListOpType = 1
	ListOpType_Delete ListOpType = 2
	ListOpType_Modify ListOpType = 3
	ListOpType_Clear  ListOpType = 4
)

// Enum value maps for ListOpType.
var (
	ListOpType_name = map[int32]string{
		0: "None",
		1: "Insert",
		2: "Delete",
		3: "Modify",
		4: "Clear",
	}
	ListOpType_value = map[string]int32{
		"None":   0,
		"Insert": 1,
		"Delete": 2,
		"Modify": 3,
		"Clear":  4,
	}
)

func (x ListOpType) Enum() *ListOpType {
	p := new(ListOpType)
	*p = x
	return p
}

func (x ListOpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListOpType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_editor_option_proto_enumTypes[0].Descriptor()
}

func (ListOpType) Type() protoreflect.EnumType {
	return &file_proto_editor_option_proto_enumTypes[0]
}

func (x ListOpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListOpType.Descriptor instead.
func (ListOpType) EnumDescriptor() ([]byte, []int) {
	return file_proto_editor_option_proto_rawDescGZIP(), []int{0}
}

type ListOpLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpType ListOpType `protobuf:"varint,1,opt,name=opType,proto3,enum=ListOpType" json:"opType,omitempty"`
	Pos    int32      `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	RefIdx int32      `protobuf:"varint,3,opt,name=ref_idx,json=refIdx,proto3" json:"ref_idx,omitempty"`
}

func (x *ListOpLog) Reset() {
	*x = ListOpLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_option_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOpLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOpLog) ProtoMessage() {}

func (x *ListOpLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_option_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOpLog.ProtoReflect.Descriptor instead.
func (*ListOpLog) Descriptor() ([]byte, []int) {
	return file_proto_editor_option_proto_rawDescGZIP(), []int{0}
}

func (x *ListOpLog) GetOpType() ListOpType {
	if x != nil {
		return x.OpType
	}
	return ListOpType_None
}

func (x *ListOpLog) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *ListOpLog) GetRefIdx() int32 {
	if x != nil {
		return x.RefIdx
	}
	return 0
}

type ListMutState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log []*ListOpLog `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty"`
}

func (x *ListMutState) Reset() {
	*x = ListMutState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_option_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMutState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMutState) ProtoMessage() {}

func (x *ListMutState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_option_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMutState.ProtoReflect.Descriptor instead.
func (*ListMutState) Descriptor() ([]byte, []int) {
	return file_proto_editor_option_proto_rawDescGZIP(), []int{1}
}

func (x *ListMutState) GetLog() []*ListOpLog {
	if x != nil {
		return x.Log
	}
	return nil
}

type MapMutState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clear    *bool    `protobuf:"varint,1,opt,name=clear,proto3,oneof" json:"clear,omitempty"`
	StrList  []string `protobuf:"bytes,2,rep,name=strList,proto3" json:"strList,omitempty"`
	I32List  []int32  `protobuf:"varint,3,rep,packed,name=i32List,proto3" json:"i32List,omitempty"`
	I64List  []int64  `protobuf:"varint,4,rep,packed,name=i64List,proto3" json:"i64List,omitempty"`
	U32List  []uint32 `protobuf:"varint,5,rep,packed,name=u32List,proto3" json:"u32List,omitempty"`
	U64List  []uint64 `protobuf:"varint,6,rep,packed,name=u64List,proto3" json:"u64List,omitempty"`
	BoolList []bool   `protobuf:"varint,7,rep,packed,name=boolList,proto3" json:"boolList,omitempty"`
}

func (x *MapMutState) Reset() {
	*x = MapMutState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_option_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapMutState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMutState) ProtoMessage() {}

func (x *MapMutState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_option_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMutState.ProtoReflect.Descriptor instead.
func (*MapMutState) Descriptor() ([]byte, []int) {
	return file_proto_editor_option_proto_rawDescGZIP(), []int{2}
}

func (x *MapMutState) GetClear() bool {
	if x != nil && x.Clear != nil {
		return *x.Clear
	}
	return false
}

func (x *MapMutState) GetStrList() []string {
	if x != nil {
		return x.StrList
	}
	return nil
}

func (x *MapMutState) GetI32List() []int32 {
	if x != nil {
		return x.I32List
	}
	return nil
}

func (x *MapMutState) GetI64List() []int64 {
	if x != nil {
		return x.I64List
	}
	return nil
}

func (x *MapMutState) GetU32List() []uint32 {
	if x != nil {
		return x.U32List
	}
	return nil
}

func (x *MapMutState) GetU64List() []uint64 {
	if x != nil {
		return x.U64List
	}
	return nil
}

func (x *MapMutState) GetBoolList() []bool {
	if x != nil {
		return x.BoolList
	}
	return nil
}

type MutState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Array map[int32]*ListMutState `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Map   map[int32]*MapMutState  `protobuf:"bytes,2,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MutState) Reset() {
	*x = MutState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_option_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MutState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutState) ProtoMessage() {}

func (x *MutState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_option_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutState.ProtoReflect.Descriptor instead.
func (*MutState) Descriptor() ([]byte, []int) {
	return file_proto_editor_option_proto_rawDescGZIP(), []int{3}
}

func (x *MutState) GetArray() map[int32]*ListMutState {
	if x != nil {
		return x.Array
	}
	return nil
}

func (x *MutState) GetMap() map[int32]*MapMutState {
	if x != nil {
		return x.Map
	}
	return nil
}

type MapKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Key:
	//
	//	*MapKey_I32
	//	*MapKey_I64
	//	*MapKey_U32
	//	*MapKey_U64
	//	*MapKey_Str
	//	*MapKey_B
	Key isMapKey_Key `protobuf_oneof:"key"`
}

func (x *MapKey) Reset() {
	*x = MapKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_editor_option_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapKey) ProtoMessage() {}

func (x *MapKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_editor_option_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapKey.ProtoReflect.Descriptor instead.
func (*MapKey) Descriptor() ([]byte, []int) {
	return file_proto_editor_option_proto_rawDescGZIP(), []int{4}
}

func (m *MapKey) GetKey() isMapKey_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (x *MapKey) GetI32() int32 {
	if x, ok := x.GetKey().(*MapKey_I32); ok {
		return x.I32
	}
	return 0
}

func (x *MapKey) GetI64() int64 {
	if x, ok := x.GetKey().(*MapKey_I64); ok {
		return x.I64
	}
	return 0
}

func (x *MapKey) GetU32() uint32 {
	if x, ok := x.GetKey().(*MapKey_U32); ok {
		return x.U32
	}
	return 0
}

func (x *MapKey) GetU64() uint64 {
	if x, ok := x.GetKey().(*MapKey_U64); ok {
		return x.U64
	}
	return 0
}

func (x *MapKey) GetStr() string {
	if x, ok := x.GetKey().(*MapKey_Str); ok {
		return x.Str
	}
	return ""
}

func (x *MapKey) GetB() bool {
	if x, ok := x.GetKey().(*MapKey_B); ok {
		return x.B
	}
	return false
}

type isMapKey_Key interface {
	isMapKey_Key()
}

type MapKey_I32 struct {
	I32 int32 `protobuf:"varint,1,opt,name=i32,proto3,oneof"`
}

type MapKey_I64 struct {
	I64 int64 `protobuf:"varint,2,opt,name=i64,proto3,oneof"`
}

type MapKey_U32 struct {
	U32 uint32 `protobuf:"varint,3,opt,name=u32,proto3,oneof"`
}

type MapKey_U64 struct {
	U64 uint64 `protobuf:"varint,4,opt,name=u64,proto3,oneof"`
}

type MapKey_Str struct {
	Str string `protobuf:"bytes,5,opt,name=str,proto3,oneof"`
}

type MapKey_B struct {
	B bool `protobuf:"varint,6,opt,name=b,proto3,oneof"`
}

func (*MapKey_I32) isMapKey_Key() {}

func (*MapKey_I64) isMapKey_Key() {}

func (*MapKey_U32) isMapKey_Key() {}

func (*MapKey_U64) isMapKey_Key() {}

func (*MapKey_Str) isMapKey_Key() {}

func (*MapKey_B) isMapKey_Key() {}

var file_proto_editor_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50200,
		Name:          "editor_gen",
		Tag:           "varint,50200,opt,name=editor_gen",
		Filename:      "proto_editor_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         50201,
		Name:          "editor_key",
		Tag:           "varint,50201,opt,name=editor_key",
		Filename:      "proto_editor_option.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional bool editor_gen = 50200;
	E_EditorGen = &file_proto_editor_option_proto_extTypes[0]
	// optional int32 editor_key = 50201;
	E_EditorKey = &file_proto_editor_option_proto_extTypes[1]
)

var File_proto_editor_option_proto protoreflect.FileDescriptor

var file_proto_editor_option_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a,
	0x09, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x4c, 0x6f, 0x67, 0x12, 0x23, 0x0a, 0x06, 0x6f, 0x70,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f,
	0x73, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x64, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x66, 0x49, 0x64, 0x78, 0x22, 0x2c, 0x0a, 0x0c, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x75, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x03, 0x6c, 0x6f,
	0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70,
	0x4c, 0x6f, 0x67, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x22, 0xd0, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x70,
	0x4d, 0x75, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x63, 0x6c, 0x65, 0x61,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6c, 0x65, 0x61, 0x72,
	0x88, 0x01, 0x01, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x69, 0x33, 0x32, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07,
	0x69, 0x33, 0x32, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x36, 0x34, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x69, 0x36, 0x34, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x33, 0x32, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x07, 0x75, 0x33, 0x32, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75,
	0x36, 0x34, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x75, 0x36,
	0x34, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x08, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x22, 0xeb, 0x01, 0x0a, 0x08,
	0x4d, 0x75, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x61, 0x72, 0x72, 0x61,
	0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4d, 0x75, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x61,
	0x72, 0x72, 0x61, 0x79, 0x12, 0x24, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x75, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x4d, 0x61, 0x70,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x1a, 0x47, 0x0a, 0x0a, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x75, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x44, 0x0a, 0x08, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x4d, 0x61, 0x70, 0x4d, 0x75, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x83, 0x01, 0x0a, 0x06, 0x4d, 0x61,
	0x70, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x33, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x03, 0x69, 0x33, 0x32, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x36, 0x34, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x69, 0x36, 0x34, 0x12, 0x12, 0x0a, 0x03,
	0x75, 0x33, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x03, 0x75, 0x33, 0x32,
	0x12, 0x12, 0x0a, 0x03, 0x75, 0x36, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52,
	0x03, 0x75, 0x36, 0x34, 0x12, 0x12, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x0e, 0x0a, 0x01, 0x62, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x01, 0x62, 0x42, 0x05, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x2a,
	0x45, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x10, 0x02, 0x12,
	0x0a, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x10, 0x04, 0x3a, 0x43, 0x0a, 0x0a, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72,
	0x5f, 0x67, 0x65, 0x6e, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x98, 0x88, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65,
	0x64, 0x69, 0x74, 0x6f, 0x72, 0x47, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x3a, 0x43, 0x0a, 0x0a, 0x65,
	0x64, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x99, 0x88, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x4b, 0x65, 0x79, 0x88, 0x01, 0x01,
	0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79,
	0x61, 0x6f, 0x67, 0x75, 0x61, 0x6e, 0x67, 0x64, 0x75, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2d, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x64, 0x65,
	0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_editor_option_proto_rawDescOnce sync.Once
	file_proto_editor_option_proto_rawDescData = file_proto_editor_option_proto_rawDesc
)

func file_proto_editor_option_proto_rawDescGZIP() []byte {
	file_proto_editor_option_proto_rawDescOnce.Do(func() {
		file_proto_editor_option_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_editor_option_proto_rawDescData)
	})
	return file_proto_editor_option_proto_rawDescData
}

var file_proto_editor_option_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_editor_option_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_editor_option_proto_goTypes = []any{
	(ListOpType)(0),                     // 0: ListOpType
	(*ListOpLog)(nil),                   // 1: ListOpLog
	(*ListMutState)(nil),                // 2: ListMutState
	(*MapMutState)(nil),                 // 3: MapMutState
	(*MutState)(nil),                    // 4: MutState
	(*MapKey)(nil),                      // 5: MapKey
	nil,                                 // 6: MutState.ArrayEntry
	nil,                                 // 7: MutState.MapEntry
	(*descriptorpb.MessageOptions)(nil), // 8: google.protobuf.MessageOptions
}
var file_proto_editor_option_proto_depIdxs = []int32{
	0, // 0: ListOpLog.opType:type_name -> ListOpType
	1, // 1: ListMutState.log:type_name -> ListOpLog
	6, // 2: MutState.array:type_name -> MutState.ArrayEntry
	7, // 3: MutState.map:type_name -> MutState.MapEntry
	2, // 4: MutState.ArrayEntry.value:type_name -> ListMutState
	3, // 5: MutState.MapEntry.value:type_name -> MapMutState
	8, // 6: editor_gen:extendee -> google.protobuf.MessageOptions
	8, // 7: editor_key:extendee -> google.protobuf.MessageOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	6, // [6:8] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_editor_option_proto_init() }
func file_proto_editor_option_proto_init() {
	if File_proto_editor_option_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_editor_option_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListOpLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_editor_option_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListMutState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_editor_option_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MapMutState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_editor_option_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*MutState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_editor_option_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*MapKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_editor_option_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_editor_option_proto_msgTypes[4].OneofWrappers = []any{
		(*MapKey_I32)(nil),
		(*MapKey_I64)(nil),
		(*MapKey_U32)(nil),
		(*MapKey_U64)(nil),
		(*MapKey_Str)(nil),
		(*MapKey_B)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_editor_option_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_editor_option_proto_goTypes,
		DependencyIndexes: file_proto_editor_option_proto_depIdxs,
		EnumInfos:         file_proto_editor_option_proto_enumTypes,
		MessageInfos:      file_proto_editor_option_proto_msgTypes,
		ExtensionInfos:    file_proto_editor_option_proto_extTypes,
	}.Build()
	File_proto_editor_option_proto = out.File
	file_proto_editor_option_proto_rawDesc = nil
	file_proto_editor_option_proto_goTypes = nil
	file_proto_editor_option_proto_depIdxs = nil
}
